print ("Hola bievenido a la calculadora básica de sumas")
num1=int (input ("Ingrese el primer número: "))
num2=int (input ("Ingrese el segundo número: "))
print ("El resultado de la suma es: ",num1+num2)
print ("pq usas un programa para hacer una mukltiplicación?🤡")